### ISSUE TITLE
Everytime I do a Full disk encryption on installing openSUSE, it always defaults to asking for the passphrase twice.

### ISSUE THREAD

**Issue by gregoriomoss** [yast/d-installer#258]

**Comment by ancorgs** [comment]
First of all, this is the repository of D-Installer, which is a prototype for the future. If you install openSUSE in 2022 you are not using D-Installer yet, but our classical installer YaST.

Having said that, the behavior of asking the passphrase twice is intentional. The first time you are providing the password to Grub2 (the boot loader). That's needed so Grub2 can load the files at `/boot` (which are encrypted) and start the booting process. The second time you are providing the password to Dracut (the component that completes the boot process, mounts file-systems, and so on).

Currently in openSUSE there is no 100% secure way for Grub2 to pass the password to Dracut, so you have to enter it twice. That could be avoided if the installer would place `/boot` in a separate non-encrypted partition. But that was discarded because it's less secure and could break the rollback functionality if you use Btrfs snapshots.

Some people configure their system following [this guide](https://en.opensuse.org/SDB:Encrypted_root_file_system#Avoiding_to_type_the_passphrase_twice_in_Leap_and_Tumbleweed) to avoid entering the password twice. Again, that behavior was not implemented in the YaST installer directly because it's considered to not be 100% secure, although it's enough for many regular users.
