### ISSUE TITLE
Security/storage settings are not changed when a product is selected

### ISSUE THREAD

**Issue by imobachgs** [yast/d-installer#311]
The storage service does not get the product configuration when a product is selected. I guess it happens since we extracted bootloader/storage/security to a separate process (see #207). It causes many side-effects, like not being able to select the proper selinux packages.

**Comment by imobachgs** [comment]
We have these options:

1) each service (e.g., storage) listens for product changes and updates its configuration on its own. The downside is that you do not know precisely when the config_phase is finished.
2) the D-Bus `Probe` method receives the product name as an argument, so the manager tells the service to update its configuration according to a given product.

There might be other options, though.

@joseivanlopez what do you think?

**Comment by imobachgs** [comment]
I have implemented the fix in #312. I manually tested the change and it seems to work. I was able to install Tumbleweed and ALP properly.

**Comment by joseivanlopez** [comment]
> We have these options:
> 
> 1. each service (e.g., storage) listens for product changes and updates its configuration on its own. The downside is that you do not know precisely when the config_phase is finished.

The problem I see with this solution is that each service has to know what to do when a new product is selected. I would prefer to not have that knowledge in the service. For example, I don't want to make the storage service aware of performing a new probing when a product is selected. It would start making everything more complex.

> 2. the D-Bus `Probe` method receives the product name as an argument, so the manager tells the service to update its configuration according to a given product.

This could be a solution, but I think that passing the product is uneccesary because it can be asked to the D-Bus software service.

> 3. the storage `probe` method asks the software service for the selected product. After all, the storage service already asks the software service to install packages and so on.

I also prefer this solution. Each service asks for the required info before performing the requested action.

BTW, I see something I don't like that much with the selection of the default product. For now, a product is selected by default only when the config file specifies a single product. That logic is duplicated in `DInstaller::Manager` and `DInstaller::Software`. I think this is error prone because we could design another different logic for selecting a default product. I would keep that responsability in `DInstaller::Software` only.

**Comment by imobachgs** [comment]
Yes, product selection is kind of tricky. We decided to postpone moving the responsibilities for later.
